theme = "papercolor-dark"

[editor]
true-color = true
cursorline = true
color-modes = true
line-number = "relative"

[keys.normal]
C-p = "file_picker"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
